releases:

- version_major: 3
  version_minor: 8
  version_patch: 0
  version_pre: 17.beta
  version_build: NULL
  name: Cardano
  about-name: |
    Cider-CI 3.8 **Cardano** is named after _Gerolamo Cardano_ an 16th century
    Italian scholar and gambler. He is recognized as one of the founders of
    probability theory in mathematics.
  description: |

    ## New Features

    * Show unavailable jobs on new job page, too.
    * Environment variables can be recursively templated.
    * Add file-templates.
    * Add statistics page for jobs.
    * Add visualization showing the dependencies of scripts.
    * Add Gantt-Diagram showing the duration of scripts.
    * Add and honor `ignore-abort` parameter to scripts.
    * Executor honors exclude/include match for checking out submodules.

    ## Fixes

    * The notifier now also supports SSH URLs (as used by GitHub)
      for notification pushing.
    * Increase timestamp precision of cache-signatures in UI.
      This fixes several caching issues in the UI.
    * Fix out of heap memory issues in the UI.
    * Fix flaky installs due to reliances problems with updating node modules.
    * Fix an issue with updating Postgresql config on Debian Jessie during
        installs and upgrades.


- version_major: 3
  version_minor: 7
  version_patch: 0
  version_pre: NULL
  version_build: NULL
  name: Redmond
  about-name: |
    Cider-CI 3.8 "Redmond" is named after the city Redmond close to
    Seatle, Washington. Readmond is the home of Microsoft which is
    mainly known for the operating system Windows.
  description: |
    Support Windows operating system on executors.
    Use id rather than name for executor authentication.
    Restructure and reorganize deploy configuration.
    Update and or rewrite large part of the documentation.
    Rewrite part of the dispatcher: improve performance and fix issue with multiple accepted_repositories.

- version_major: 3
  version_minor: 6
  version_patch: 0
  version_pre: NULL
  version_build: NULL
  name: Peacock
  description: |
    * New "My Workspace" page replaces commits and jobs page.
    * Improve UX and UI.
    * Remove (now superfluous) radiator.
    * Reorganize storage tables.

- version_major: 3
  version_minor: 5
  version_patch: 0
  version_pre: NULL
  version_build: NULL
  description: |
    Add abort action and related.
    Improve internal error handling.
    Abort trials when executor looses them or even disappears.
    Rewrite sweepers.
    Improve deploy/setup via Ansible.
    Update extend install documentation.

- version_major: 3
  version_minor: 4
  version_patch: 0
  version_pre: NULL
  version_build: NULL
  description: |
    * Filter commits by distance to branch head.
    * Rework fetch-and-update in repository service.
    * Fix import: a deep commit history and limited RAM could blow the stack
      or memory and terminate the import irrecoverably.
    * Add pull mode for executor operation (BETA).
    * Jobs can depend on other jobs in submodules (BETA).

- version_major: 3
  version_minor: 3
  version_patch: 0
  version_pre: NULL
  version_build: NULL
  description: |
    Rename dotfile to project configuration (file).
    Accept also JSON configuration files.
    Accept unhidden project configuration files.
    Move project-configuration building over to repository service.
    Fix tasks pagination in job view.

- version_major: 3
  version_minor: 2
  version_patch: 0
  version_pre: NULL
  version_build: NULL
  description: |
    The accept repositories feature is stable.
    Update repository on notification (BETA).
    Push statuses to GitHub (BETA).

- version_major: 3
  version_minor: 1
  version_patch: 0
  version_pre: NULL
  version_build: NULL
  description: |
    Task generation via git ls-tree.
    Use tree-id for triggering jobs instead of raw events.
    Executor can specify accepted repositories (BETA).
    Improve setup and deploy with Ansible.

- version_major: 3
  version_minor: 0
  version_patch: 0
  version_pre: NULL
  version_build: NULL
  description: |
    Rename executions to jobs. Rewrite database schema. Redefine job
    dependencies. Rewrite script execution on executors.  Replace commons/exec
    termination with custom code. Introduce script dependencies instead of
    fixed order. Rewrite dotfile specification. Remove deprecated dotfile
    features.

- version_major: 2
  version_minor: 4
  version_patch: 1
  version_pre: NULL
  version_build: NULL
  description: |
    Fix link to releases on public page. Fix naming in documentation.

- version_major: 2
  version_minor: 4
  version_patch: 0
  version_pre: NULL
  version_build: NULL
  description: |
    Improve repository handling with respect to stability and performance on
    executors. Improve submodule handling and performance.

- version_major: 2
  version_minor: 3
  version_patch: 2
  version_pre: NULL
  version_build: NULL
  description:  |
    Add cider-ci dotfile and honor execution definitions.
    Accept maps for tasks and subcontexts.
    Randomize and improve dispatching.
    Honor exclusive_resources.
    Support git sumodules.
  git_ref: "cider-ci_2.3.2"


- version_major: 2
  version_minor: 2
  version_patch: 0
  version_pre: ""
  version_build: ""
  description:  >
    Improve UI for multi execution processes.
    Add result field (json) to trials / tasks / executions.
    New summary as svg badge and html, show result too.
    git_ref: "cider-ci_2.2.0"

- version_major: 2
  version_minor: 1
  version_patch: 0
  version_pre: ""
  version_build: ""
  description:  >
    Public view permission for executions and related resources.
    Generalize svg with styles for img tag embedding.
    Enable bootstrap themes.
  git_ref: "cider-ci_2.1.0"

- version_major: 2
  version_minor: 0
  version_patch: 0
  version_pre: ""
  version_build: ""
  description:  >
    Add builder. Introduce new specification format.
    Move API from HAL to JSON-ROA.
    Change PUT on Storage-API to REST sematics (no conflict).
    Support Debian Wheezy.
  git_ref: "master"

- version_major: 1
  version_minor: 7
  version_patch: 2
  version_pre: ""
  version_build: ""
  description:  >
    Fix link to trial_attachments in API.
  git_ref: "1.7.2"

- version_major: 1
  version_minor: 7
  version_patch: 1
  version_pre: ""
  version_build: ""
  description:  >
    Improve performance, improve progressive ui, improve reloader.
  git_ref: "1.7.1"

- version_major: 1
  version_minor: 7
  version_patch: 0
  version_pre: ""
  version_build: ""
  description:  >
    Add API. Add tree attachments.
  git_ref: "1.7.0"

- version_major: 1
  version_minor: 6
  version_patch: 1
  version_pre: ""
  version_build: ""
  description:  >
    Fix git fetch on executor.
  git_ref: "1.6.1"

- version_major: 1
  version_minor: 6
  version_patch: 0
  version_pre: ""
  version_build: ""
  description:  >
    Security improvements: authenticate and authorize between executors
    and server, use https throughout when not communicating within
    localhost. Refacor and clean-up executor code.
  git_ref: "1.6.0"


- version_major: 1
  version_minor: 5
  version_patch: 0
  version_pre: ""
  version_build: ""
  description:  >
                  Disect into services.
                  Do not run within and remove dependency on Jboss/Polyglot.
  git_ref: "1.5.0"

- version_major: 1
  version_minor: 4
  version_patch: 5
  description:  >
                  Change repo locations. Minor fixes.

- version_major: 1
  version_minor: 4
  version_patch: 4
  description:  >
                Welcome page with custom section and radiator.
                Result bars in execution overview.
                Per page filter on executions and tasks.
                Css and icon fixes. Improved reloader.
                Blacklist some env vars on the executors.
                Tags are links.

- version_major: 1
  version_minor: 4
  version_patch: 3
  description:  >
                Move server-settings from database to config file.

- version_major: 1
  version_minor: 4
  version_patch: 2
  description:  >
                Delete scrips of a trial after a configurable retention time.

- version_major: 1
  version_minor: 4
  version_patch: 1
  description:  >
                Auto tag executions with branch and repo. Minor UI improvements.
                Timeout ping requests. Reinitialize repo when not present.

- version_major: 1
  version_minor: 4
  version_patch: 0
  description:  >
                UI and some UX overhaul. Simplify reloader and
                involved javascript.

- version_major: 1
  version_minor: 3
  version_patch: 2
  description:  >
                Executor inherits HOME and USER to shell.  Revamped
                sourcing and layout wrt local login, rc and profile files.

- version_major: 1
  version_minor: 3
  version_patch: 1
  description: >
               Ascertain lost trials and revamp dispatching.  Send trial
               status on request; revert to non interactive shell by default.
               Revamp of welcome/about page.

- version_major: 1
  version_minor: 3
  version_patch: 0
  description: >
               Ascertain lost trials and revamped dispatching on server-im.
               Send trial status on request; revert to non interactive shell
               by default on executor.
